services:
  dev:
    image: mcr.microsoft.com/devcontainers/javascript-node:22
    ports:
      - "5003:5002"
      - "9124:8123"
    environment:
      IS_SANDBOX: "1"
    volumes:
      - ..:/workspaces/PNut-Term-TS:cached
    command: sleep infinity
